#!/usr/bin/env node
/**
 * Build the dashboard view the MCP endpoint serves to Claude and ChatGPT (MCP Apps), and embed
 * the plugin's files, as two generated modules:
 *
 *   lib/mcp-apps/dashboard-html.generated.ts   the view: one self-contained HTML document
 *   lib/plugin/plugin-files.generated.ts       the plugin's skills and README, as strings
 *
 *   npm run mcp:app
 *
 * WHY THE OUTPUT IS COMMITTED. Both are read by API routes at request time. A route cannot rely
 * on a file beside it being traced into a serverless bundle, and this app is deployed by people
 * who click a button, not by people who run a build step first. A module is always there. The
 * cost is that the sources and the output can drift, which lib/mcp-apps/generated.test.ts
 * prevents: it rebuilds in memory and fails when the committed files differ.
 *
 * The view:
 *   1. esbuild bundles lib/mcp-apps/app/main.ts for the browser (no framework, about 30 KB).
 *   2. The token blocks of app/globals.css (`:root` and `.dark`) are lifted out and put in front
 *      of lib/mcp-apps/app/styles.css, so the view's colours ARE the app's tokens.
 *   3. Script and style are inlined into one document. It loads nothing from the network, which
 *      is what lets its content-security policy be empty (lib/mcp-apps/server.ts).
 */
import { build, transform } from 'esbuild'
import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8')

const HEADER = '// GENERATED by scripts/build-mcp-app.mjs. Do not edit: change the sources and run `npm run mcp:app`.\n'

// ---------------------------------------------------------------------------------------------
// Tokens
// ---------------------------------------------------------------------------------------------

/** The body of the first `selector { … }` block that declares `--background`. */
function tokenBlock(css, selector) {
  let from = 0
  for (;;) {
    const at = css.indexOf(`${selector} {`, from)
    if (at < 0) throw new Error(`app/globals.css has no "${selector} {" block declaring --background`)
    // Only at the start of a line: `.dark select:not(…) {` is a rule, not the token block.
    const lineStart = css.lastIndexOf('\n', at) + 1
    const open = at + selector.length + 1
    let depth = 1
    let i = open + 1
    for (; i < css.length && depth > 0; i++) {
      if (css[i] === '{') depth++
      else if (css[i] === '}') depth--
    }
    const body = css.slice(open + 1, i - 1)
    if (css.slice(lineStart, at).trim() === '' && /--background\s*:/.test(body)) return body
    from = at + 1
  }
}

/** Only the custom-property declarations, comments removed. */
function declarations(body) {
  return body
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .split(';')
    .map(d => d.trim())
    .filter(d => /^--[a-z0-9-]+\s*:/.test(d))
    .join(';')
}

export function tokenCss() {
  const css = read('app', 'globals.css')
  const light = declarations(tokenBlock(css, ':root'))
  const dark = declarations(tokenBlock(css, '.dark'))
  for (const name of ['--card', '--foreground', '--muted-foreground', '--border', '--primary', '--cat-1', '--warning', '--radius', '--radius-card']) {
    if (!new RegExp(`${name}\\s*:`).test(light)) throw new Error(`app/globals.css :root no longer declares ${name}, which the dashboard view uses`)
  }
  // The app loads Inter through next/font and names it by a variable the view does not have.
  // Without this the whole --font-sans stack would be invalid, not just its first family.
  return `:root{--font-inter:'Inter';${light}}.dark{${dark}}`
}

// ---------------------------------------------------------------------------------------------
// The view
// ---------------------------------------------------------------------------------------------

export async function buildDashboardHtml() {
  const js = await build({
    entryPoints: [path.join(root, 'lib', 'mcp-apps', 'app', 'main.ts')],
    bundle: true,
    minify: true,
    write: false,
    format: 'iife',
    platform: 'browser',
    target: ['es2020'],
    legalComments: 'none',
    tsconfig: path.join(root, 'tsconfig.json'),
  })
  const css = await transform(`${tokenCss()}\n${read('lib', 'mcp-apps', 'app', 'styles.css')}`, { loader: 'css', minify: true })

  // Neither may close its own element early. No source contains these today; a company name in
  // a future string literal should not be what finds out.
  const script = js.outputFiles[0].text.replace(/<\/(script)/gi, '<\\/$1')
  const style = css.code.replace(/<\/(style)/gi, '<\\/$1')

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<meta name="color-scheme" content="light dark">',
    '<title>Portfolio dashboards</title>',
    `<style>${style.trim()}</style>`,
    '</head>',
    '<body>',
    '<div id="app"></div>',
    `<script>${script.trim()}</script>`,
    '</body>',
    '</html>',
    '',
  ].join('\n')
}

export async function dashboardModule() {
  const html = await buildDashboardHtml()
  const hash = crypto.createHash('sha256').update(html).digest('hex').slice(0, 12)
  return [
    HEADER,
    '/** First 12 hex characters of the SHA-256 of DASHBOARD_HTML: the cache key in its ui:// address. */',
    `export const DASHBOARD_HTML_HASH = ${JSON.stringify(hash)}`,
    '',
    `export const DASHBOARD_HTML = ${JSON.stringify(html)}`,
    '',
  ].join('\n')
}

// ---------------------------------------------------------------------------------------------
// The plugin's files
// ---------------------------------------------------------------------------------------------

function walk(dir, base = dir) {
  return fs.readdirSync(dir, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name))
    .flatMap(entry => {
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) return walk(full, base)
      return [[path.relative(base, full).split(path.sep).join('/'), fs.readFileSync(full, 'utf8')]]
    })
}

/** Every file under plugin/, by its path inside the plugin. */
export function pluginModule() {
  const files = Object.fromEntries(walk(path.join(root, 'plugin')))
  return [
    HEADER,
    '/** The plugin\'s static files (skills, README), keyed by path inside the plugin. Source: plugin/. */',
    `export const PLUGIN_FILES: Record<string, string> = ${JSON.stringify(files, null, 2)}`,
    '',
  ].join('\n')
}

export const OUTPUTS = {
  dashboard: path.join(root, 'lib', 'mcp-apps', 'dashboard-html.generated.ts'),
  plugin: path.join(root, 'lib', 'plugin', 'plugin-files.generated.ts'),
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const dashboard = await dashboardModule()
  const plugin = pluginModule()
  fs.mkdirSync(path.dirname(OUTPUTS.plugin), { recursive: true })
  fs.writeFileSync(OUTPUTS.dashboard, dashboard)
  fs.writeFileSync(OUTPUTS.plugin, plugin)
  const kb = n => `${(Buffer.byteLength(n) / 1024).toFixed(1)} KB`
  console.log(`dashboard view  ${kb(dashboard)}  ${path.relative(root, OUTPUTS.dashboard)}`)
  console.log(`plugin files    ${kb(plugin)}  ${path.relative(root, OUTPUTS.plugin)}`)
}
